# Generated by Django 6.0.6 on 2026-06-24 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bridge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الجسر')),
                ('code', models.CharField(blank=True, max_length=40, verbose_name='الرمز')),
                ('status', models.CharField(choices=[('operational', 'تشغيلي'), ('maintenance', 'تحت الصيانة'), ('critical', 'حالة حرجة')], default='operational', max_length=20, verbose_name='الحالة')),
                ('length_m', models.PositiveIntegerField(default=0, verbose_name='الطول (م)')),
                ('lanes', models.PositiveIntegerField(default=0, verbose_name='عدد المسارات')),
                ('opened_year', models.CharField(blank=True, max_length=10, verbose_name='سنة الافتتاح')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('path', models.JSONField(default=list, verbose_name='مسار الرسم')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'جسر',
                'verbose_name_plural': 'الجسور',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Defect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان العيب')),
                ('severity', models.CharField(choices=[('high', 'عالية'), ('medium', 'متوسطة'), ('low', 'منخفضة')], default='medium', max_length=10, verbose_name='الخطورة')),
                ('status', models.CharField(choices=[('open', 'مفتوح'), ('in_progress', 'تحت المعالجة'), ('resolved', 'تم الإصلاح')], default='open', max_length=15, verbose_name='الحالة')),
                ('date', models.DateField(blank=True, null=True, verbose_name='التاريخ')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('location', models.JSONField(blank=True, default=list, verbose_name='الموقع')),
                ('bridge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defects', to='bridges.bridge', verbose_name='الجسر')),
            ],
            options={
                'verbose_name': 'عيب',
                'verbose_name_plural': 'العيوب',
            },
        ),
        migrations.CreateModel(
            name='DefectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='defects/', verbose_name='الصورة')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='وصف الصورة')),
                ('defect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='bridges.defect', verbose_name='العيب')),
            ],
            options={
                'verbose_name': 'صورة عيب',
                'verbose_name_plural': 'صور العيوب',
            },
        ),
    ]
