# Generated by Django 6.0.6 on 2026-06-24 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridges', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bridge',
            name='code',
        ),
        migrations.RemoveField(
            model_name='bridge',
            name='description',
        ),
        migrations.RemoveField(
            model_name='bridge',
            name='lanes',
        ),
        migrations.RemoveField(
            model_name='bridge',
            name='length_m',
        ),
        migrations.RemoveField(
            model_name='bridge',
            name='opened_year',
        ),
        migrations.RemoveField(
            model_name='bridge',
            name='path',
        ),
        migrations.RemoveField(
            model_name='defect',
            name='date',
        ),
        migrations.RemoveField(
            model_name='defect',
            name='location',
        ),
        migrations.RemoveField(
            model_name='defect',
            name='severity',
        ),
        migrations.AddField(
            model_name='bridge',
            name='lat',
            field=models.FloatField(default=21.4275, verbose_name='خط العرض'),
        ),
        migrations.AddField(
            model_name='bridge',
            name='lng',
            field=models.FloatField(default=39.8235, verbose_name='خط الطول'),
        ),
        migrations.AddField(
            model_name='defect',
            name='area_m2',
            field=models.FloatField(default=0, verbose_name='المساحة (م²)'),
        ),
        migrations.AddField(
            model_name='defect',
            name='count',
            field=models.PositiveIntegerField(default=0, verbose_name='العدد'),
        ),
        migrations.AddField(
            model_name='defect',
            name='length_m',
            field=models.FloatField(default=0, verbose_name='الطول (م)'),
        ),
        migrations.AddField(
            model_name='defect',
            name='width_m',
            field=models.FloatField(default=0, verbose_name='العرض (م)'),
        ),
        migrations.AlterField(
            model_name='defect',
            name='title',
            field=models.CharField(max_length=200, verbose_name='اسم العيب'),
        ),
    ]
