# Generated by Django 6.0.6 on 2026-06-26 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridges', '0002_remove_bridge_code_remove_bridge_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Road',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment', models.CharField(max_length=200, verbose_name='المقطع')),
                ('status', models.CharField(choices=[('critical', 'حرج'), ('medium', 'متوسط'), ('low', 'منخفض')], default='medium', max_length=20, verbose_name='الحالة')),
                ('direction', models.CharField(choices=[('mecca', 'مكة'), ('jeddah', 'جدة')], default='mecca', max_length=20, verbose_name='الاتجاه')),
                ('observation', models.CharField(blank=True, help_text='اسفلت - أصول جانبي الطريق', max_length=255, verbose_name='الملاحظة')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('lat', models.FloatField(default=21.4275, verbose_name='خط العرض')),
                ('lng', models.FloatField(default=39.8235, verbose_name='خط الطول')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'طريق',
                'verbose_name_plural': 'الطرق',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='bridge',
            name='status',
            field=models.CharField(choices=[('critical', 'حرج'), ('operational', 'ضعيف'), ('maintenance', 'مقبول'), ('good', 'جيد')], default='operational', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='defect',
            name='status',
            field=models.CharField(choices=[('open', 'مفتوح'), ('in_progress', 'جاري المعالجة'), ('resolved', 'منتهى')], default='open', max_length=15, verbose_name='الحالة'),
        ),
    ]
