# Generated by Django 6.0.6 on 2026-06-26 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridges', '0003_road_alter_bridge_status_alter_defect_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bridge',
            name='description',
            field=models.TextField(blank=True, verbose_name='الوصف'),
        ),
    ]
