# Generated by Django 6.0.6 on 2026-06-26 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridges', '0004_bridge_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoadDefect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='اسم/عنوان الحالة')),
                ('status', models.CharField(choices=[('critical', 'حرج'), ('medium', 'متوسط'), ('low', 'منخفض')], default='medium', max_length=20, verbose_name='الحالة')),
                ('direction', models.CharField(choices=[('mecca', 'مكة'), ('jeddah', 'جدة')], default='mecca', max_length=20, verbose_name='الاتجاه')),
                ('observation', models.CharField(blank=True, help_text='اسفلت - أصول جانبي الطريق', max_length=255, verbose_name='الملاحظة')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('treatment_type', models.CharField(blank=True, max_length=255, verbose_name='نوع المعالجة')),
                ('road', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defects', to='bridges.road', verbose_name='الطريق')),
            ],
            options={
                'verbose_name': 'حالة طريق',
                'verbose_name_plural': 'حالات الطرق',
            },
        ),
        migrations.CreateModel(
            name='RoadDefectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='road_defects/', verbose_name='الصورة')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='وصف الصورة')),
                ('defect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='bridges.roaddefect', verbose_name='الحالة')),
            ],
            options={
                'verbose_name': 'صورة حالة طريق',
                'verbose_name_plural': 'صور حالات الطرق',
            },
        ),
    ]
