# Generated by Django 6.0.6 on 2026-06-26 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridges', '0005_roaddefect_roaddefectimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='road',
            options={'verbose_name': 'طريق', 'verbose_name_plural': 'الطرق'},
        ),
        migrations.RemoveField(
            model_name='road',
            name='description',
        ),
        migrations.RemoveField(
            model_name='road',
            name='direction',
        ),
        migrations.RemoveField(
            model_name='road',
            name='observation',
        ),
        migrations.AlterField(
            model_name='roaddefect',
            name='treatment_type',
            field=models.CharField(choices=[('treated', 'معالج'), ('untreated', 'غير معالج')], default='untreated', max_length=20, verbose_name='نوع المعالجة'),
        ),
    ]
