# Generated by Django 6.0.6 on 2026-06-28 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridges', '0006_alter_road_options_remove_road_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roaddefect',
            name='lat',
            field=models.FloatField(default=21.38866, verbose_name='خط العرض'),
        ),
        migrations.AddField(
            model_name='roaddefect',
            name='lng',
            field=models.FloatField(default=39.42683, verbose_name='خط الطول'),
        ),
    ]
