# Generated by Django 6.0.6 on 2026-06-29 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridges', '0009_move_direction_to_road'),
    ]

    operations = [
        migrations.AddField(
            model_name='roaddefect',
            name='direction',
            field=models.CharField(choices=[('mecca', 'مكة'), ('jeddah', 'جدة')], default='mecca', max_length=20, verbose_name='الاتجاه'),
        ),
    ]
