# Generated by Django 6.0.6 on 2026-07-06 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridges', '0010_roaddefect_direction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lighting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100, verbose_name='رقم العمود/البرج')),
                ('type', models.CharField(choices=[('pole', 'عمود'), ('tower', 'برج')], default='pole', max_length=20, verbose_name='النوع')),
                ('lat', models.FloatField(default=21.4275, verbose_name='خط العرض')),
                ('lng', models.FloatField(default=39.8235, verbose_name='خط الطول')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'إنارة',
                'verbose_name_plural': 'الإنارة',
                'ordering': ['-created_at'],
            },
        ),
    ]
