# Generated by Django 6.0.6 on 2026-07-07 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridges', '0011_lighting'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم النطاق')),
                ('geom', models.JSONField(default=list, verbose_name='الإحداثيات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'نطاق',
                'verbose_name_plural': 'النطاقات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=300, verbose_name='اسم المشروع')),
                ('value', models.FloatField(default=0.0, verbose_name='قيمة صرف العقد')),
                ('department', models.CharField(blank=True, max_length=200, verbose_name='الادارة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('zones', models.ManyToManyField(related_name='contracts', to='bridges.zone', verbose_name='النطاقات')),
            ],
            options={
                'verbose_name': 'عقد',
                'verbose_name_plural': 'العقود',
                'ordering': ['-created_at'],
            },
        ),
    ]
