# Generated by Django 6.0.6 on 2026-07-07 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridges', '0012_zone_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='color',
            field=models.CharField(default='#3b82f6', max_length=20, verbose_name='لون الخط'),
        ),
    ]
