# Generated by Django 6.0.6 on 2026-07-07 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridges', '0013_zone_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='حالة العقد'),
        ),
    ]
