# Generated by Django 6.0.6 on 2026-07-08 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridges', '0014_contract_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='category',
            field=models.CharField(choices=[('current', 'الحالية'), ('new2028', 'الجديدة 2028')], default='current', max_length=20, verbose_name='التصنيف'),
        ),
        migrations.AddField(
            model_name='zone',
            name='category',
            field=models.CharField(choices=[('current', 'الحالية'), ('new2028', 'الجديدة 2028')], default='current', max_length=20, verbose_name='التصنيف'),
        ),
    ]
