# Generated by Django 6.0.6 on 2026-07-08 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridges', '0015_contract_category_zone_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract',
            options={'ordering': ['order', '-created_at'], 'verbose_name': 'عقد', 'verbose_name_plural': 'العقود'},
        ),
        migrations.AddField(
            model_name='contract',
            name='order',
            field=models.IntegerField(default=0, verbose_name='الترتيب'),
        ),
    ]
